### ISSUE TITLE
Using ruff and flake8 together?

### ISSUE THREAD

**Issue by HomerusJa** [cleder/python-repository-template#1]
In your test-build-publish.yml action you are linting with flake8 and then with ruff:

```yaml
# Line 64
      - name: Linting
        run: |
          uv run flake8 src/PROJECT_NAME tests --max-line-length=88
          uv run ruff check --no-fix src/PROJECT_NAME tests
          uv run ruff format --check src/PROJECT_NAME tests
  
# …
```

Just asking why it is like that. To my knowledge, ruff has integrated most (if not all) flake8 rules. Why would you bother with two different tools, two different configurations which might conflict each other? Are there any shortcomings from ruff you see which you think you need to compensate by using flake8 directly?

Thanks for helping!
